DATA     EQU     $6000
PROGRAM  EQU     $4000

         ORG     DATA
START    DS.L    1               ADDRESS OF STRING
LENGTH   DS.W    1               NUMBER OF CHARACTERS IN STRING

CR       EQU     $0D             ASCII VALUE FOR CARRIAGE RETURN

         ORG     PROGRAM

PGM_6_1C MOVEA.L START,A0        POINTER TO START OF STRING
         MOVEQ   #-1,D2          INITIALIZE MAX STRING LENGTH = 256
         MOVE.W  D2,D0           LENGTH COUNT := MAX STRING LENGTH
         MOVEQ   #CR,D1          INITIALIZE STRING WITH ASCII VALUE OF CR

* SCAN STRING FOR CARRIAGE RETURN. STOP SCAN WHEN
* CARRIAGE RETURN FOUND OR 256 CHARACTERS SCANNED.

LOOP     CMP.B   (A0)+,D1        IS CURRENT CHART A CARRIAGE RETURN?
         DBEQ    D0,LOOP         IF NO AND NOT END OF STRING - CONT.

         SUB.W   D0,D2                DETERMINE STRING LENGTH
         MOVE.W  D2,LENGTH            SAVE STRING LENGTH

         RTS

         END     PGM_6_1C
