DATA     EQU     $6000
PROGRAM  EQU     $4000

         ORG     DATA
NUMBER   DS.L    1               ADDRESS OF NUMBER TO BE NORMALIZED
NORMNUM  DS.L    1               NORMALIZED NUMBER
SHIFTNUM DS.B    1               NUMBER OF SHIFTS REQUIRED TO NORMALIZE

         ORG     PROGRAM

PGM_5_5  MOVEQ   #0,D0           INITIALIZE SHIFT COUNT
         MOVEA.L NUMBER,A0       GET ADDRESS OF NUMBER TO NORMALIZE
         MOVE.L  (A0),D1         GET NUMBER TO BE NORMALIZED
         BLE.S   DONE            IF ZERO OR NORMALIZED THEN DONE

JUSTIFY  ADDQ.W  #1,D0           INCREMENT SHIFT COUNT
         LSL.L   #1,D1           SHIFT NUMBER 1 BIT TO THE LEFT
         BPL     JUSTIFY         AGAIN IF MSB = 0

DONE     MOVE.B  D0,SHIFTNUM     STORE SHIFT COUNT
         MOVE.L  D1,NORMNUM      STORE NORMALIZED NUMBER

         RTS

         END     PGM_5_5
