DATA     EQU     $6000
PROGRAM  EQU     $4000

         ORG     DATA
LENGTH   DS.W    1               NUMBER OF DATA ELEMENTS
START    DS.L    1               ADDRESS OF DATA ELEMENTS
TOTAL    DS.L    1               SUM OF DATA ELEMENTS
CARRYBIT EQU     $10000          CARRY BIT VALUE

         ORG     PROGRAM

PGM_5_2A MOVEA.L START,A0        INITIALIZE POINTER REGISTER
         MOVEQ   #0,D0           INITIALIZE SUM TO ZERO
         MOVE.W  LENGTH,D1       INITIALIZE ELEMENT COUNT

         BEQ.S   DONE            IF LENGTH = 0 THEN DONE

LOOP     ADD.W   (A0)+,D0        SUM NEXT ELEMENT
         BCC.S   LOOPTEST        IF CARRY = 0 THEN GOTO LOOPTEST

         ADDI.L  #CARRYBIT,D0    ...ELSE ADD 16-BIT CARRY

LOOPTEST SUBQ.W  #1,D1           UPDATE ELEMENT COUNT
         BNE     LOOP            IF COUNT NOT ZERO THEN GOTO LOOP

DONE     MOVE.L  D0,TOTAL        STORE SUMMATION

         RTS

         END     PGM_5_2A
