DATA     EQU     $6000
PROGRAM  EQU     $4000

         ORG     DATA
LENGTH   DS.W    1               NUMBER OF DATA ELEMENTS
START    DS.L    1               ADDRESS OF DATA ELEMENTS
TOTAL    DS.W    1               SUM OF DATA ELEMENTS

         ORG     PROGRAM

PGM_5_3  MOVEA.L START,A0        INITIALIZE POINTER REGISTER
         MOVEQ   #0,D0           NNEG := 0
         MOVE.W  LENGTH,D1       INITIALIZE ELEMENT COUNT
         BEQ.S   DONE            IF LENGTH = 0 THEN DONE

LOOP     TST.W   (A0)+           TEST DATA ELEMENT
         BPL.S   LOOPTEST        IF > 0 THEN GOTO LOOPTEST

         ADDQ.W  #1,D0           ..ELSE NNEG := NNEG +1

LOOPTEST SUBQ.W  #1,D1             UPDATE ELEMENT COUNT
         BNE     LOOP            IF COUNT NOT ZERO THEN GOTO LOOP

DONE     MOVE.W  D0,TOTAL        STORE NUMBER OF NEGATIVE ELEMENTS

         RTS

         END     PGM_5_3
